name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  job-main:
    name: Build Site
    runs-on: macOS-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: ruby versions
        run: |
          ruby --version
          gem --version
          bundler --version

      - name: cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-

      - name: bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: jekyll build
        run: bundle exec jekyll build
