name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  job-main:
    name: Build Site
    # https://github.com/actions/virtual-environments/tree/main/images/macos
    runs-on: macOS-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: ruby versions
        run: |
          ruby --version
          gem --version
          bundler --version

      - name: cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-bundler2214-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-bundler2214-

      - name: bundle install
        run: |
          # gem update --system
          gem install bundler --no-document
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: jekyll build
        run: bundle exec jekyll build --verbose --trace
